./bin/pathtrace -r 360 -s 256 -i naive -p -o out/cornell_box_naive.png in/cornell_box/cornell_box.obj
./bin/pathtrace -r 360 -s 256 -i product -p -o out/cornell_box_product.png in/cornell_box/cornell_box.obj
./bin/pathtrace -r 360 -s 256 -i direct -p -o out/cornell_box_direct.png in/cornell_box/cornell_box.obj
./bin/pathtrace -r 360 -s 256 -i direct -p -o out/simple_pointlight_direct.png in/simple_pointlight/simple_pointlight.obj
./bin/pathtrace -r 360 -s 256 -i mis -p -o out/simple_arealight_mis.png in/simple_arealight/simple_arealight.obj
./bin/pathtrace -r 360 -s 256 -i mis -p -o out/simple_envlight_mis.png in/simple_envlight/simple_envlight.obj
./bin/pathtrace -r 360 -s 256 -i direct -p -o out/matball_plastic03_arealight_direct.png in/matball_plastic03_arealight/matball_plastic03_arealight.obj
./bin/pathtrace -r 360 -s 256 -i mis -p -o out/matball_gold02_arealight_mis.png in/matball_gold02_arealight/matball_gold02_arealight.obj
./bin/pathtrace -r 360 -s 256 -i mis -p -o out/matball_silver01_arealight_mis.png in/matball_silver01_arealight/matball_silver01_arealight.obj
./bin/pathtrace -r 360 -s 256 -i direct -p -o out/matball_plastic03_envlight_direct.png in/matball_plastic03_envlight/matball_plastic03_envlight.obj
./bin/pathtrace -r 360 -s 256 -i direct -p -o out/matball_gold02_envlight_direct.png in/matball_gold02_envlight/matball_gold02_envlight.obj
./bin/pathtrace -r 360 -s 256 -i direct -p -o out/matball_silver01_envlight_direct.png in/matball_silver01_envlight/matball_silver01_envlight.obj
